(defun most (fn lst)
  (cond ((null lst) (values nil  nil))
	(t
	 (let* ((wins (car lst))
		(max (funcall fn (car lst))))
	   (dolist (obj (cdr lst))
	     (let ((score (funcall fn obj)))
	       (when (> score max)
		 (setf wins obj)
		 (setf max score))))
	   (values wins max)))))
(defun remove-from-list (obj lst)
  (if (null lst) nil
      (if (= obj (car lst))
	  (cdr lst)
	  (cons obj (remove-from-list obj (cdr lst))))))
(defun most-modified (fn lst)
  (multiple-value-bind (x y) (most fn lst)
  (multiple-value-bind (v w) (most fn (remove-from-list x lst))
  (values x v))))