(defun tree-map(function tree)
  (cond ((nil? tree) nil)
	((not (consp tree)) (funcall function tree))
	(t (cons (tree-map function (car tree)) 
		 (tree-map function(cdr tree))))))
(defun square (x)
  (* x x))
(defun square-tree-alt (tree)
  (tree-map #'square tree))