(defun make-point (x y)
  (cons x y))
(defun x-point (point)
  (car point))
(defun y-point (point)
  (cdr point))
(defun make-segment (p1 p2)
  (cons p1 p2))
(defun start-segment (s)
  (car s))
(defun end-segment (s)
  (cdr s))
(defun midpoint-segment (s)
  (make-point (average (x-point (start-segment s)) (x-point (end-segment s)))
	      (average (y-point (start-segment s)) (y-point (end-segment s)))))
(defun average (x y)
  (/ (+ x y) (* 2 1.0)))